### PR TITLE
Add -b (begin at), -d (duration) and -w (width) options

### PR DESCRIPTION
**Pull request by winder**
Thanks for this tool, it's just what I needed!

There were a few additional options I wanted to use, so I updated the script to use them.

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks, these options look great.

Could you quickly explain how cut and duration work? Maybe add examples for them in the help output too?

e.g If I have a 10 second clip and use `-d 5` do I just get the last 5 seconds?Does '-c 5' cut and throw away the first 5 seconds or are they cut to be used in the GIF. How do they function when used together?

Have you checked the leading comma in `scale` doesn't cause issues if other values like fps are unset?

**Comment by winder** [comment]
Sure. I updated the documentation. And here is a more detailed explanation.

Cut and duration pass through directly to the ffmpeg -t and -ss options, and are intended to work together to select a window in the input for processing:
```
-t duration         record or transcode "duration" seconds of audio/video
-ss time_off        set the start time offset
```

I would have named them `-t` and `-ss` (if you provide invalid inputs ffmpeg mentions -ss and -t directly in the error), but getopts doesn't seem to support multi-character options. I suppose I could at least change `-d` to `-t`, what do you think?

The answer to your other questions is yes. Cut specifies a number of seconds to cut and discard from the beginning of the input video. Now that you ask the question I see that it wasn't clear, this option isn't like cut/paste. Offset might be a better name, but `o` was already used for the output file option.

Duration is the length of the input video to use, this one is probably more obvious, but that it works well with cut wasn't clear.

For a more detailed usage example, the gif I wanted yesterday was from a 40 second screen recording, I wanted it to start at 0:08 and only wanted it to be 14 seconds long. Using cut/duration I can achieve the result using this command:
```
./gifgen -c 8 -d 12 input.mp4
```

Thanks for pointing out the possible comma/fps issue. I gave it a try and ffmpeg doesn't seem to care if you have something like `fps=,,scale=320:-1:flags=lanczos`. So we're good there!

**Comment by lukechilds** [comment]
Awesome!

I'm not worried to much about mapping 1:1 to ffmpeg args, they can be pretty cryptic.

Cut is slightly confusing with regards to if you're yanking that bit out to throw away or to keep. Although you have now clarified it in the help text.

How about `-d` for "duration" and `-s` for "start at"?

Also are you able to remove the version number change from this branch? I normally keep each branch/PR as a single atomic change and squash it into a single clearly names commit in master.

I'll do a new commit/tag for the version number change.

Then this is ready to merge!

**Comment by winder** [comment]
`-s` is already taken with the static background option, so I renamed `cut` -> `begin` which is hopefully a more intuitive name.

**Comment by lukechilds** [comment]
@winder perfect, thanks!

**Pull request merged**
